### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/r2-streamer-swift#1]
Now that the code is on the Readium repo, I'd like to make sure that all Readium-2 projects have a license associated to the code, ideally a very open one (MIT or BSD).

**Comment by jce1028** [comment]
All things considered MIT seems the way to go unless we are have a fear of brand diminution of Readium with the use of the R2 SDK.  I think the opposite is the case, however.

**Comment by whmccoy** [comment]
Hi, I think we need to separate three issues here:

1. Do we want a default fully permissive license? (no copyleft nor even
requirement to contribute back changes)?

2. If so do we want to stick with BSD as we have for other
permissively-licensed components or go with MIT, Apache, or something else?

3. Do we want a dual-license model as with original Readium SDK (default
non-commercial-friendly license and alternative that is commercial-friendly
that is not free)?

I think question #2 is the least interesting question but if it comes down
to this question I don't know that I agree with James about going with MIT
rather than sticking with BSD are sufficiently valuable to warrant further
complexifying what is already a complicated open source model (we presently
use three different licenses: BSD, GNU Affero, and the Apache-based
Alternative License). At least we should IMO only do this if there are
specific benefits of MIT vs. BSD that are worth the pain of having to
explain 4 different licenses, beyond just personal preference or style, and
I haven't heard what these benefits are.

**Comment by HadrienGardeur** [comment]
My point was not about MIT vs BSD, but the requirement for a license on every repo that we host on this organization.

I'm perfectly happy with BSD if it makes things any easier but just to be clear:

1. I'm against using a complex license like we did with Readium SDK where one part was dual-license (C++) and the rest was BSD (Javascript)
2. for projects where Feedbooks has contributed 100% of the development time so far (which is not the case at all on the Swift streamer, which was entirely developed and funded by Olivier and EDRLab), I'll only accept a fully permissive license (BSD or MIT)

Ideally, I'd like all Readium-2 projects to use a fully permissive license, no matter if we're releasing code, specifications, documentations or examples.
