### ISSUE TITLE
Documentation url doesn't work

### ISSUE THREAD

**Issue by meruiden** [readium/r2-streamer-swift#157]
the url provided in Readme.md pointing to your documentation does not seem to work anymore

**Comment by mickael-menu** [comment]
I don't think this is maintained anymore.

The only documentation we have is the `README.md` in the project which should be enough to get you started, otherwise you have to browse through the code.

You can generate the documentation yourself if needed following these instructions: https://github.com/readium/r2-streamer-swift#documentation
