### ISSUE TITLE
Add support for canonical form of the manifest

### ISSUE THREAD

**Issue by ghost** [readium/r2-streamer-swift#36]
Most implementations of the streamer generate a pretty printed output of the Readium Web Publication Manifest.

To facilitate testing across implementations, we want to add a canonical output of that same manifest with the following rules:

remove all whitespaces between keys/values
alphanumeric sorting based on the keys
remove links
remove URI scheme & host (http://localhost:3692 for example)
We'll use the canonical query parameter to determinate when we should generate this canonical form: http://www.example.com/manifest.json?canonical=true.

**Comment by camill-a** [comment]
ObjectMapper doesn't implement orderedMap. Partially fixed in e9f3ba4

**Comment by gbugniot** [comment]
So, according to commit e9f3ba4
- Remove all whitespaces between keys/values is **done**
- Alphanumeric sorting based on the keys is **done**
- Remove links is **done**
- Remove URI scheme & host is **not done**, need more context to be sure

**Comment by gbugniot** [comment]
There is no easy solution to sort keys of a JSON with Swift. JSON is built from a `dictionary` which is a non ordered type. Since the canonical form of the manifest is for testing purposes, I will temporarily move this issue to the icebox.

**Comment by danielweck** [comment]
What about using:
```swift
let jsonEncoder = JSONEncoder()
jsonEncoder.outputFormatting = .sortedKeys
```
https://developer.apple.com/documentation/foundation/jsonencoder
?

**Comment by gbugniot** [comment]
I'm aware of this API, but you're right to mention it.

It was introduced last year, and therefore it's compatible with [iOS 11 and later](https://developer.apple.com/documentation/foundation/jsonencoder/outputformatting/2919670-sortedkeys), however our requirement is to support iOS >= 9. One more thing on this, I've already made some test with this API and I was not able to produce an output sorted without pretty-printing it.

Moreover, our Swift code base does not rely on `JSONEncoder` but on a third party dependancy called [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper). There is also [an issue on sorting keys for JSON](https://github.com/Hearst-DD/ObjectMapper/issues/512) with this lib. It's in [our backlog](https://github.com/readium/r2-shared-swift/issues/3) to move away from `ObjectMapper` to use the new [Codable](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) protocol (which btw is also used by `JSONEncoder`), so I guess we should first migrate to `Codable`, then see if it's worth spending more time on trying to sort JSON keys.

**Comment by mickael-menu** [comment]
As stated in this issue, it's difficult to produce a reliable canonical JSON with native Swift APIs, especially before iOS 11.

At the moment the parser is mostly covered with unit tests and we don't need a canonical manifest anymore.

However if we really want to share some test cases across platforms at some point, I'll suggest that instead of exposing a canonical manifest API we:

* require the tests to be run on iOS 11+ (this is already the case)
* parse the shared canonical JSON with `JSONSerialization`
* compare the output of the RWPM parser and the parsed canonical JSON using [`assertJSONEqual`](https://github.com/readium/r2-shared-swift/blob/8065a61e72b46214a71f7128c8ce1594fc30c85d/r2-shared-swiftTests/Asserts.swift#L14-L23)
