### ISSUE TITLE
OPF metadata parsing (otherMetadata)

### ISSUE THREAD

**Issue by danielweck** [readium/r2-streamer-swift#95]
The current parsing code hard-codes support for `dc:source` and `dc:rights`, but there are many other possibilities such as `cc:attributionURL` (`<package prefix="cc: http://creativecommons.org/ns#">`), `a11y:certifiedBy` ( http://www.idpf.org/epub/vocab/package/a11y/# ), `dcterms:conformsTo`, ` schema:accessModeSufficient`, etc.

Any `<meta property="NAME">VALUE</meta>` or `<meta name="NAME" value="VALUE">` not "natively" supported should be passed to `otherMetadata`, without hard-coding particular names.

https://github.com/readium/r2-streamer-swift/blob/1cc6dc1c683b12592b052c80669302f9c36efcdd/Sources/parser/EPUB/OPFParser.swift#L89-L93

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/r2-shared-js/issues/16

**Comment by danielweck** [comment]
Regarding `dc:source` and `dc:rights`, see: https://github.com/readium/webpub-manifest/issues/14

**Comment by mmenu-mantano** [comment]
https://github.com/readium/r2-streamer-swift/pull/105 fixes this partially. `<meta property="x"/>` are added to `otherMetadata`, but `dc:source` and `dc:rights` are still hard-coded because they can appear like that: `<dc:rights>Public domain</dc:rights>`. Additional discussion regarding this can be found here: https://github.com/readium/webpub-manifest/issues/14#issuecomment-498591021
